"""empty message

Revision ID: 9a9724acaaec
Revises: 
Create Date: 2025-12-22 17:38:06.661144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a9724acaaec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcripts_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcripts_transcript_text'), ['transcript_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcripts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcripts_user_id'))
        batch_op.drop_index(batch_op.f('ix_transcripts_transcript_text'))
        batch_op.drop_index(batch_op.f('ix_transcripts_session_id'))

    op.drop_table('transcripts')
    # ### end Alembic commands ###
